`RuntimeError`と表示される
