`ArgumentError`が発生する